"""Re-pin the map goldens after an intended change (V2 §45).

Rewrites the DrawPlan snapshots and relief signatures under tests/goldens/, and drops
the reference pictures under docs/reference/ so the change can be *looked at* — the
diff of the JSON and the pair of pictures are the review artefacts.

    python scripts/regenerate_goldens.py            # everything
    python scripts/regenerate_goldens.py alps renn  # just these worlds
    python scripts/regenerate_goldens.py --no-maps  # skip the slow full-map renders

Two kinds of picture come out of here. The relief PNGs are the raster alone, cheap,
and pinned by hash as well. The full-map renders go through the parity renderer —
the real /api/map, DrawPlan and stylesheet path — and are the only artefact that
shows composition, type, colour and presentation together, which is where the last
three phases' defects were actually spotted. They were regenerated by hand and so
went stale by a phase and a half; running them from here is what stops that.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))
sys.path.insert(0, str(ROOT / "scripts"))

import goldenlib  # noqa: E402

REFERENCE = ROOT / "docs" / "reference"


# The named views: which corpus world, at which band, in which theme. Chosen to cover
# what the reference set has to answer for — a dense political core, a mountain
# frontier, a long coast, a civil war, and Renn at all three bands.
VIEWS = (
    ("renn-regional", "regional", False),
    ("renn-world", "world", False),
    ("renn-local", "local", False),
    ("renn-night", "regional", True),
    ("alps", "regional", False),
    ("long_coast", "regional", False),
    ("civil_war", "regional", False),
    ("empire-world", "world", False),
)


def _draw_map(world, label: str, band: str, dark: bool) -> None:
    """One reference picture, through the parity renderer the client mirrors."""
    import render_map

    data, relief, png = render_map.the_map(
        world, day=None, mode="legally_owns", seen_as=None, scale=6)
    css = render_map.stylesheet_colours(dark=dark)
    svg = render_map.render_svg(data, relief, png, css=css, mode="legally_owns",
                                width=1500, band=band)
    out = REFERENCE / f"map-{label}.png"
    behind = css.get("map-sea", "#4a6580") if png else css.get("panel", "#ffffff")
    if not render_map.rasterise(svg, out, behind):
        out = out.with_suffix(".svg")
        out.write_text(svg)
    print(f"  docs/reference/{out.name}")


def main() -> int:
    argv = [a for a in sys.argv[1:] if not a.startswith("--")]
    maps = "--no-maps" not in sys.argv
    chosen = set(argv)
    for name in goldenlib.DRAWPLAN_WORLDS:
        if chosen and name not in chosen:
            continue
        world = goldenlib.accepted(name)
        try:
            goldenlib.write_golden("drawplan", name,
                                   goldenlib.drawplan_snapshot(world))
            print(f"drawplan/{name} pinned")
            if name in goldenlib.RELIEF_WORLDS:
                goldenlib.write_golden("relief", name, {
                    "scale": goldenlib.RELIEF_SCALE,
                    "signature": goldenlib.relief_signature(world),
                })
                from fw.core.mapgen import raster

                REFERENCE.mkdir(parents=True, exist_ok=True)
                picture = goldenlib.render_ground(world)
                png = raster.encode(picture.width, picture.height, picture.pixels)
                (REFERENCE / f"relief-{name}.png").write_bytes(png)
                print(f"relief/{name} pinned (+ docs/reference/relief-{name}.png)")
            if maps:
                for label, band, dark in VIEWS:
                    if label.split("-")[0] != name:
                        continue
                    _draw_map(world, label, band, dark)
        finally:
            world.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
